import Head from "next/head";
import Navbar from "../components/Navbar";
import classes from "../styles/Home.module.scss";
import AvatarShapes from "../public/photo-bg.svg";

import { useEffect, useState } from "react";
import Hero from "../components/sections/Hero";
import About from "../components/sections/About";
import Jobs from "../components/sections/Jobs";

export default function Home() {
  const [open, setOpen] = useState(false);
  useEffect(() => {
    if (open) {
      document.querySelector("body").classList.add("blurred");
    } else {
      document.querySelector("body").classList.remove("blurred");
    }
  }, [open]);
  return (
    <>
      <Head>
        <title>Amine Louni</title>
        <meta name="description" content="Generated by Amine Louni" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={open && classes.blurred}>
        <Navbar open={open} setOpen={setOpen} />
        <Hero />

        <About />

        <Jobs />
      </main>
      <footer>footer</footer>
    </>
  );
}
